meta_product_name: "GamerCouch"
meta_title: "GamerCouch - Find the right games for you"
meta_description: "Find the games matching your personal tastes"
meta_image: "og_photo.png" # should exist in `app/assets/images/`
